from os import environ

AZURE_SPEECH_RECOGNITION_KEY = environ.get("AZURE_SPEECH_RECOGNITION_KEY")
AZURE_SPEECH_RECOGNITION_LOCATION = environ.get("AZURE_SPEECH_RECOGNITION_LOCATION")
ARDUINO_PORT = environ.get("ARDUINO_PORT")